routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::post('/auth/register/getType', 'App\Http\Controllers\Auth\RegisterController@getType')->name('getType');
Route::post('/admin/categories/getCategory', 'App\Http\Controllers\Admin\CategoriesController@getCategory')->name('getCategory');
Auth::routes();

Route::middleware('auth')->get('/home', 'App\Http\Controllers\HomeController@index')->name('home');
Route::middleware('auth')->post('/admin/categories/createcategoria', 'App\Http\Controllers\Admin\CategoriesController@createcategoria')->name('createcategoria');
Route::middleware('auth')->post('/admin/categorie/deleteCategorie', 'App\Http\Controllers\Admin\CategoriesController@deleteCategorie')->name('deleteCategorie');
Route::middleware('auth')->post('/admin/specialties/createspecialty', 'App\Http\Controllers\Admin\SpecialtiesController@createspecialty')->name('createspecialty');
Route::middleware('auth')->post('/admin/specialties/deletespecialty', 'App\Http\Controllers\Admin\SpecialtiesController@deletespecialty')->name('deletespecialty');
Route::middleware('auth')->post('/admin/independents/addIndependent', 'App\Http\Controllers\Admin\IndependentsController@addIndependent')->name('addIndependent');
Route::middleware('auth')->post('/admin/independents/deleteAvailableTime', 'App\Http\Controllers\Admin\IndependentsController@deleteAvailableTime')->name('deleteAvailableTime');
Route::middleware('auth')->post('/admin/independents/deleteImg', 'App\Http\Controllers\Admin\IndependentsController@deleteImg')->name('deleteImg');
Route::middleware('auth')->post('/admin/independents/consultAvailableTime', 'App\Http\Controllers\Admin\IndependentsController@consultAvailableTime')->name('consultAvailableTime');
Route::middleware('auth')->get('/admin/independents/profile/{id}', 'App\Http\Controllers\Admin\IndependentsController@profile')->name('profile');
Route::middleware('auth')->get('/admin/independents/occupation/{id}', 'App\Http\Controllers\Admin\IndependentsController@occupation')->name('occupation');
Route::middleware('auth')->post('/admin/ratings/createrating', 'App\Http\Controllers\Admin\RatingsController@createrating')->name('createrating');
Route::group(['middleware' => ['auth']], function() {
    Route::resource('/admin/categories', 'App\Http\Controllers\Admin\CategoriesController');
    Route::resource('/admin/companies', 'App\Http\Controllers\Admin\CompaniesController');
    Route::resource('/admin/specialties', 'App\Http\Controllers\Admin\SpecialtiesController');
    Route::resource('/admin/independents', 'App\Http\Controllers\Admin\IndependentsController');
    Route::resource('/admin/ratings', 'App\Http\Controllers\Admin\RatingsController');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Independent.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Specialty;

class Independent extends Model
{
    protected $guard = 'admin';

    protected $fillable = [
        'id',
        'user_id',
        'name',
        'city',
        'phone',
        'email',
        'identification',
        'specialties_id',
        'images',
        'categories_id',
        'is_active'
    ];

    protected $hidden = [
        'created_at',
        'updated_at',
    ];

    protected $guarded = [
        'id',
        'created_at',
        'updated_at'
    ];

    protected $dates  = [
        'created_at',
        'updated_at'
    ];
    public function specialties()
    {
        return $this->belongsTo(Specialty::class)
            ->select(['id', 'name']);
    }
}

app/Http/Controllers/Admin/IndependentsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Company;
use App\Http\Controllers\Controller;
use App\Independent;
use App\Specialty;
use App\CompanyIndependent;
use App\AvailableTime;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class IndependentsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $specialties = Specialty::select('*')->where('type', 'empl')->orderBy('id', 'desc')->get();
        $independents = Independent::select('*')->orderBy('id', 'desc')->get();
        $user = Auth::user();
        $company = Company::select('*')->where('email', $user->email)->get();
        $independent = Independent::select('*')->where('email', $user->email)->get();
        return view('admin.independents.index', compact('independents', 'company', 'specialties', 'independent', 'user'));
    }

    public function create()
    {
        $user = Auth::user();
        $specialties = Specialty::select('*')->where('type', 'empl')->orderBy('id', 'desc')->get();
        $categories = Category::select('*')->where('type', 'empl')->orderBy('id', 'desc')->get();
        $company = Company::select('*')->where('email', $user->email)->get();
        $independent = Independent::select('*')->where('email', $user->email)->get();
        return view('admin.independents.create', compact('specialties', 'categories', 'user', 'company', 'independent'));
    }

    public function store(Request $request)
    {
        $independent = new Independent();
        $independent->user_id = $request->user_id;
        $independent->name = $request->name;
        $independent->phone = $request->phone;
        $independent->city = $request->city;
        $independent->email = $request->email;
        $independent->identification = $request->identification;
        $independent->specialties_id = $request->specialties_id;
        $independent->categories_id = $request->categories_id;
        $independent->images = $request->images;
        $independent->save();
        $independents = Independent::select('*')->orderBy('id', 'desc')->get();
        $user = Auth::user();
        $company = Company::select('*')->where('email', $user->email)->get();
        $independent = Independent::select('*')->where('email', $user->email)->get();
        return view('home', compact('independents','company', 'independent', 'user'));
    }

    public function edit($id){
        $indep = Independent::findOrFail($id);
        $user = Auth::user();
        $specialties = Specialty::select('*')->where('type', 'empl')->orderBy('id', 'desc')->get();
        $categories = Category::select('*')->where('type', 'empl')->orderBy('id', 'desc')->get();
        $company = Company::select('*')->where('email', $user->email)->get();
        $independent = Independent::select('*')->where('email', $user->email)->get();
        $availableTime = AvailableTime::select('*')->where('independent_id',$id)->get();
        return view('admin.independents.update', compact('company','indep','specialties', 'categories', 'user','independent','availableTime'));
    }
    public function consultAvailableTime(Request $request){
        if ($request->get('id')) {
            $id = $request->get('id');
            $availableTime = AvailableTime::select('*')->where('independent_id',$id)->get();
            return response()->json($availableTime);
        }
    }
    public function addIndependent(Request $request)
    {
        if ($request->get('id')) {
            $id = $request->get('id');
            $user = Auth::user();
            $company = Company::select('id')->where('user_id', $user->id)->first();
            $id_company = $company['id'];
            $companyIndependent = new CompanyIndependent();
            $companyIndependent->independent_id = $id;
            $companyIndependent->company_id = $id_company;
            $companyIndependent->available_time_id = $request->get('ids');
            $companyIndependent->save();
        }
    }
    public function profile($id){
        $specialties = Specialty::select('*')->where('type', 'empl')->orderBy('id', 'desc')->get();
        $independentinfo = Independent::select('*')->where('id', $id)->first();
        $user = Auth::user();
        $company = Company::select('*')->where('email', $user->email)->get();
        $independent = Independent::select('*')->where('email', $user->email)->get();
        return view('admin.independents.profile', compact('independentinfo', 'company', 'specialties', 'independent', 'user'));
    }
    public function occupation($id){
        $independentinfo = Independent::select('*')->where('id', $id)->first();
        $user = Auth::user();
        $company = Company::select('*')->where('email', $user->email)->get();
        $independent = Independent::select('*')->where('email', $user->email)->get();
        $availableTime = AvailableTime::select('*')->where('independent_id',$id)->get();
        return view('admin.independents.occupation', compact('company','independentinfo', 'user','independent','availableTime'));
    }
    public function update(Request $request, $id)
    {
        $indep = Independent::findOrFail($id);
        $indep->user_id = $request->user_id;
        $indep->name = $request->name;
        $indep->phone = $request->phone;
        $indep->city = $request->city;
        $indep->email = $request->email;
        $indep->identification = $request->identification;
        $indep->specialties_id = $request->specialties_id;
        $indep->categories_id = $request->categories_id;
        $imgs = '';
        // File upload configuration
        $targetDir = base_path() . "/public/images/jobs_independents/";
        $allowTypes = array('jpg', 'png', 'jpeg', 'gif');
        $fileNames = array_filter($_FILES['files']['name']);
        if (!empty($fileNames)) {
            foreach ($_FILES['files']['name'] as $key => $val) {
                // File upload path
                $fileName = basename($_FILES['files']['name'][$key]);
                $targetFilePath = $targetDir . $fileName;
                if ($key == 0) {
                    $imgs = $fileName;
                } else {
                    $imgs = $imgs . ' / ' . $fileName;
                }
                // Check whether file type is valid
                $fileType = pathinfo($targetFilePath, PATHINFO_EXTENSION);
                if (in_array($fileType, $allowTypes)) {
                    // Upload file to server
                    move_uploaded_file($_FILES["files"]["tmp_name"][$key], $targetFilePath);
                } else {
                    echo 'Error al guardar imgs trabajos ';
                }
            }
        }
        if ($imgs != '') {
            $indep->images = $imgs . ' / ' . $request->images;
        }
        $indep->save();

        $specialties = Specialty::select('*')->where('type', 'empl')->orderBy('id', 'desc')->get();
        $independents = Independent::select('*')->orderBy('id', 'desc')->get();
        $user = Auth::user();
        $company = Company::select('*')->where('email', $user->email)->get();
        $independent = Independent::select('*')->where('email', $user->email)->get();
        $conta = 0;
        if ($request->days1 != '') {
            $conta=1;
        }
        if ($request->days2 != '') {
            $conta = 2;
        }
        if ($request->days3 != '') {
            $conta = 3;
        }
        if ($request->days4 != '') {
            $conta = 4;
        }
        if ($request->days5 != '') {
            $conta = 5;
        }
        if ($request->days6 != '') {
            $conta = 6;
        }
        if ($request->days7 != '') {
            $conta = 7;
        }
        if ($request->days8 != '') {
            $conta = 8;
        }
        if ($request->days9 != '') {
            $conta = 9;
        }
        if ($request->days10 != '') {
            $conta = 10;
        }
        if ($request->days11 != '') {
            $conta = 11;
        }
        if ($request->days12 != '') {
            $conta = 12;
        }
        $data = $request->all();
        $i = 1;
        $ind = $id;
        for ($i = 1; $i <= $conta; $i++) {
            $availabletime = $data;
            $d = 'days' . $i;
            $st = 'start_time' . $i;
            $et = 'end_time' . $i;
            $availabletime['days'] = $request->$d;
            $availabletime['start_time'] = $request->$st;
            $availabletime['end_time'] = $request->$et;
            $availabletime['independent_id'] = $ind;
            $avail = AvailableTime::create($availabletime);
        }
        return view('home', compact('independents', 'company', 'specialties', 'independent', 'user'));
    }
    public function deleteAvailableTime(Request $request)
    {
        if ($request->get('id')) {
            $id = $request->get('id');
            $availabletime = AvailableTime::findOrFail($id);
            $availabletime->delete();
        }
    }
    public function deleteImg(Request $request)
    {
        if ($request->get('delimg')) {
            $delimg = $request->get('delimg');
            $img = $delimg;
            $ruta = base_path() . '/public/images/jobs_independents/' . $img;
            unlink($ruta);
            $id = $request->get('ida');
            $uimgs = $request->get('uimgs');
            $independent = Independent::findOrFail($id);
            $independent->url_imgs = $uimgs;
            if ($independent->save()) {
                $resp = 'Foto eliminado correctamente';
            } else {
                $resp = 'La foto no pudo ser eliminado';
            }
        }
    }
}

resources/views/admin/independents/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="content-wrapper">
        <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Crear Empleado Independiente</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form  action="{{ route('independents.store') }}" method="POST" enctype="multipart/from-data">
                @csrf
              <div class="card-body">
                <div class="row">
                    <div class="col-12 col-sm-4">
                        <div class="form-group">
                            <label for="name">Nombre</label>
                            <input type="text" class="form-control" id="name" name="name">
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group">
                            <label for="phone">Telefóno</label>
                            <input type="text" class="form-control" id="phone" name="phone">
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group">
                            <label for="city">Ciudad</label>
                            <input type="text" class="form-control" id="city" name="city">
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email" class="form-control" id="email" name="email">
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group">
                            <label for="identification">Identificación</label>
                            <input type="text" class="form-control" id="identification" name="identification">
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group">
                            <label for="specialties_id">Especialidad</label>
                            <select name="specialties_id" id="specialties_id" class="form-control" enabled>
                                @foreach($specialties as $specialty)
                                    <option value="{{ $specialty->id }}">{{ $specialty->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group">
                            <label for="categories_id">Categoria</label>
                            <select name="categories_id" id="categories_id" class="form-control" enabled>
                                @foreach($categories as $category)
                                    <option value="{{ $category->id }}">{{ $category->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group">
                            <label for="images">Imagenes Trabajos</label>
                            <div class="input-group">
                              <div class="custom-file">
                                <input type="file" class="custom-file-input" id="images">
                                <label class="custom-file-label" for="images">Cargar logo</label>
                              </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-header">
                    <h3 class="card-title">Agregar Horarios de Disponibilidad</h3>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-12">
                            <div class="form-group">
                                <label>Escoger Días</label>
                                <input name="WorkWeek" class="form-control days-of-week" id="WorkWeek" type="text" value="" data-bind="value: WorkWeek">
                            </div>
                        </div>
                        <div class="col-12 col-sm-6">
                            <div class="form-group">
                                <label for="images">Horario Inicio</label>
                                <input type="time" class="form-control">
                            </div>
                        </div>
                        <div class="col-12 col-sm-6">
                            <div class="form-group">
                                <label for="images">Horario Fin</label>
                                <input type="time" class="form-control">
                            </div>
                        </div>
                        <div class="col-12 col-sm-6">
                            <button type="button" class="btn btn-block btn-primary">Agregar más horarios de disponibilidad</button>
                        </div>
                    </div>
                </div>
              </div>
              <!-- /.card-body -->

              <div class="card-footer">
                  <div class="row">
                    <div class="col-12 text-center">
                        <input type="hidden" class="user_id" id="user_id" name="user_id" value="{{ $user->id }}">
                        <button type="submit" class="btn btn-primary">Guardar</button>
                    </div>
                  </div>
              </div>
            </form>
          </div>
    </div>
    <script>
        (function( $ ){

        "use strict";

        $.fn.daysOfWeekInput = function() {
        return this.each(function(){
            var $field = $(this);

            var days = [
            {
                Name: 'Domingo',
                Value: 'D',
                Checked: false
            },
            {
                Name: 'Lunes',
                Value: 'L',
                Checked: false
            },
            {
                Name: 'Martes',
                Value: 'M',
                Checked: false
            },
            {
                Name: 'Miercoles',
                Value: 'W',
                Checked: false
            },
            {
                Name: 'Jueves',
                Value: 'J',
                Checked: false
            },
            {
                Name: 'Viernes',
                Value: 'V',
                Checked: false
            },
            {
                Name: 'Sábado',
                Value: 'S',
                Checked: false
            }
            ];

            var currentDays = $field.val().split('');
            for(var i = 0; i < currentDays.length; i++) {
            var dayA = currentDays[i];
            for(var n = 0; n < days.length; n++) {
                var dayB = days[n];
                if(dayA === dayB.Value) {
                dayB.Checked = true;
                }
            }
            }

            // Make the field hidden when in production.
            //$field.attr('type','hidden');

            var options = '';
            var n = 0;
            while($('.days' + n).length) {
            n = n + 1;
            }

            var optionsContainer = 'days' + n;
            $field.before('<div class="days ' + optionsContainer + '"></div>');

            for(var i = 0; i < days.length; i++) {
            var day = days[i];
            var id = 'day' + day.Name + n;
            var checked = day.Checked ? 'checked="checked"' : '';
            options = options + '<div><input type="checkbox" value="' + day.Value + '" id="' + id + '" ' + checked + ' /><label for="' + id + '">' + day.Name + '</label>&nbsp;&nbsp;</div>';
            }

            $('.' + optionsContainer).html(options);

            $('body').on('change', '.' + optionsContainer + ' input[type=checkbox]', function () {
            var value = $(this).val();
            var index = getIndex(value);
            if(this.checked) {
                updateField(value, index);
            } else {
                updateField(' ', index);
            }
            });

            function getIndex(value) {
            for(i = 0; i < days.length; i++) {
                if(value === days[i].Value) {
                return i;
                }
            }
            }

            function updateField(value, index) {
            $field.val($field.val().substr(0, index) + value + $field.val().substr(index+1)).change();
            }
        });
        }

        })( jQuery );

        $('.days-of-week').daysOfWeekInput();
    </script>
@endsection

resources/views/admin/independents/occupation.blade.php
<?php
    use App\CompanyIndependent;
    use App\Company;
?>
@extends('layouts.app')
@section('content')
    <div class="content-wrapper">
        <!-- Main content -->
        <section class="content">
            @if(!$availableTime->isEmpty())
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Estado Horarios Disponibilidad</h3>
                    </div>
                    <div class="card-body">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th class="pl-5">Días</th>
                                    <th class="text-center">Hora Inicio</th>
                                    <th class="text-center">Hora Fin</th>
                                    <th class="text-center">Empresa</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($availableTime as $av)
                                    <tr>
                                        <td>{{ $av->days }}</td>
                                        <td class="text-center">{{ $av->start_time }}</td>
                                        <td class="text-center">{{ $av->end_time }}</td>
                                        <td class="text-center">
                                            <?php $companyIndependent = CompanyIndependent::select('available_time_id','company_id')->where('independent_id',$independentinfo['id'])->get(); ?>
                                            @if(!$companyIndependent->isEmpty())
                                                <?php $arr; ?>
                                                @foreach($companyIndependent as $ci)
                                                    <?php
                                                        $arr = explode("-",$ci['available_time_id']);
                                                        $size = count($arr);
                                                        for($i = 0;$i < $size;$i++){
                                                            if($arr[$i] == $av->id){
                                                                $ncompany = Company::select('name')->where('id',$ci['company_id'])->first();
                                                                echo $ncompany['name'];
                                                            }
                                                        }
                                                    ?>
                                                @endforeach
                                            @endif

                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                        <input type="hidden" name="idselected" id="idselected">
                    </div>
                </div>
              @else
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Estado Horarios Disponibilidad</h3>
                    </div>
                    <div class="card-body">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th class="pl-5">Días</th>
                                    <th class="text-center">Hora Inicio</th>
                                    <th class="text-center">Hora Fin</th>
                                    <th class="text-center">Empresa</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
              @endif
        </section>
    </div>
@endsection