routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::post('/auth/register/getType', 'App\Http\Controllers\Auth\RegisterController@getType')->name('getType');
Route::post('/admin/categories/getCategory', 'App\Http\Controllers\Admin\CategoriesController@getCategory')->name('getCategory');
Auth::routes();

Route::middleware('auth')->get('/home', 'App\Http\Controllers\HomeController@index')->name('home');
Route::middleware('auth')->post('/admin/categories/createcategoria', 'App\Http\Controllers\Admin\CategoriesController@createcategoria')->name('createcategoria');
Route::middleware('auth')->post('/admin/categorie/deleteCategorie', 'App\Http\Controllers\Admin\CategoriesController@deleteCategorie')->name('deleteCategorie');
Route::middleware('auth')->post('/admin/specialties/createspecialty', 'App\Http\Controllers\Admin\SpecialtiesController@createspecialty')->name('createspecialty');
Route::middleware('auth')->post('/admin/specialties/deletespecialty', 'App\Http\Controllers\Admin\SpecialtiesController@deletespecialty')->name('deletespecialty');
Route::middleware('auth')->post('/admin/independents/addIndependent', 'App\Http\Controllers\Admin\IndependentsController@addIndependent')->name('addIndependent');
Route::middleware('auth')->post('/admin/independents/deleteAvailableTime', 'App\Http\Controllers\Admin\IndependentsController@deleteAvailableTime')->name('deleteAvailableTime');
Route::middleware('auth')->post('/admin/independents/deleteImg', 'App\Http\Controllers\Admin\IndependentsController@deleteImg')->name('deleteImg');
Route::middleware('auth')->post('/admin/independents/consultAvailableTime', 'App\Http\Controllers\Admin\IndependentsController@consultAvailableTime')->name('consultAvailableTime');
Route::middleware('auth')->get('/admin/independents/profile/{id}', 'App\Http\Controllers\Admin\IndependentsController@profile')->name('profile');
Route::middleware('auth')->get('/admin/independents/occupation/{id}', 'App\Http\Controllers\Admin\IndependentsController@occupation')->name('occupation');
Route::middleware('auth')->post('/admin/ratings/createrating', 'App\Http\Controllers\Admin\RatingsController@createrating')->name('createrating');
Route::group(['middleware' => ['auth']], function() {
    Route::resource('/admin/categories', 'App\Http\Controllers\Admin\CategoriesController');
    Route::resource('/admin/companies', 'App\Http\Controllers\Admin\CompaniesController');
    Route::resource('/admin/specialties', 'App\Http\Controllers\Admin\SpecialtiesController');
    Route::resource('/admin/independents', 'App\Http\Controllers\Admin\IndependentsController');
    Route::resource('/admin/ratings', 'App\Http\Controllers\Admin\RatingsController');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Specialty;

class Company extends Model
{
    protected $guard = 'admin';

    protected $fillable = [
        'id',
        'user_id',
        'name',
        'city',
        'phone',
        'email',
        'web_site',
        'specialties_id',
        'facebook',
        'instagram',
        'images',
        'contact',
        'address',
        'categories_id',
        'is_active'
    ];

    protected $hidden = [
        'created_at',
        'updated_at',
    ];

    protected $guarded = [
        'id',
        'created_at',
        'updated_at'
    ];

    protected $dates  = [
        'created_at',
        'updated_at'
    ];
    public function specialties()
    {
        return $this->belongsTo(Specialty::class)
            ->select(['id', 'name']);
    }
}

app/Http/Controllers/Admin/CompaniesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Company;
use App\Http\Controllers\Controller;
use App\Specialty;
use App\Independent;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class CompaniesController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $specialties = Specialty::select('*')->where('type', 'empr')->orderBy('id', 'desc')->get();
        $companies = Company::select("*")->orderBy('id', 'desc')->get();
        $user = Auth::user();
        $company = Company::select('*')->where('email', $user->email)->get();
        $independent = Independent::select('*')->where('email', $user->email)->get();
        return view('admin.companies.index', compact('company', 'specialties', 'independent', 'user', 'companies'));
    }

    public function create()
    {
        $user = Auth::user();
        $specialties = Specialty::select('*')->where('type', 'empr')->orderBy('id', 'desc')->get();
        $categories = Category::select('*')->where('type', 'empr')->orderBy('id', 'desc')->get();
        $company = Company::select('*')->where('email', $user->email)->get();
        $independent = Independent::select('*')->where('email', $user->email)->get();
        return view('admin.companies.create', compact('specialties', 'categories', 'user', 'company','independent'));
    }

    public function store(Request $request)
    {
        $c = new Company();
        $c->user_id = $request->user_id;
        $c->name = $request->name;
        $c->phone = $request->phone;
        $c->city = $request->city;
        $c->email = $request->email;
        $c->address = $request->address;
        $c->web_site = $request->web_site;
        $c->facebook = $request->facebook;
        $c->instagram = $request->instagram;
        $c->contact = $request->contact;
        $c->specialties_id = $request->specialties_id;
        $c->categories_id = $request->categories_id;
        $c->save();
        //$company = Company::select('*')->orderBy('id', 'desc')->get();
        $specialties = Specialty::select('*')->where('type', 'empr')->orderBy('id', 'desc')->get();
        $user = Auth::user();
        $company = Company::select('*')->where('email', $user->email)->get();
        $independent = Independent::select('*')->where('email', $user->email)->get();
        return view('home', compact('company', 'specialties','independent','user'));
    }

    public function edit($id)
    {
        $comp = Company::findOrFail($id);
        $user = Auth::user();
        $specialties = Specialty::select('*')->where('type', 'empr')->orderBy('id', 'desc')->get();
        $categories = Category::select('*')->where('type', 'empr')->orderBy('id', 'desc')->get();
        $company = Company::select('*')->where('email', $user->email)->get();
        $independent = Independent::select('*')->where('email', $user->email)->get();
        return view('admin.companies.update', compact('company','comp','specialties', 'categories', 'user','independent'));
    }

    public function update(Request $request, $id)
    {
        $comp = Company::findOrFail($id);
        $comp->name = $request->name;
        $comp->phone = $request->phone;
        $comp->city = $request->city;
        $comp->email = $request->email;
        $comp->address = $request->address;
        $comp->web_site = $request->web_site;
        $comp->facebook = $request->facebook;
        $comp->instagram = $request->instagram;
        $comp->contact = $request->contact;
        $comp->specialties_id = $request->specialties_id;
        $comp->categories_id = $request->categories_id;
        if($request->file('logo') != ""){
            $logo = $request->name.'.' .$request->file('logo')->guessExtension();
            $request->file('logo')->move(
                base_path().'/public/images/logos_companies/', $logo
            );
            $comp->images = $logo;
        }
        $comp->save();
        $specialties = Specialty::select('*')->where('type', 'empr')->orderBy('id', 'desc')->get();
        $companies = Company::select("*")->orderBy('id', 'desc')->get();
        $user = Auth::user();
        $company = Company::select('*')->where('email', $user->email)->get();
        $independent = Independent::select('*')->where('email', $user->email)->get();
        return view('home', compact('company', 'specialties', 'independent', 'user', 'companies'));
    }
}

resources/views/admin/companies/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="content-wrapper">
        <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Crear Empresa</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form  action="{{ route('companies.store') }}" method="POST" enctype="multipart/from-data">
                @csrf
              <div class="card-body">
                <div class="row">
                    <div class="col-12 col-sm-4">
                        <div class="form-group">
                            <label for="name">Nombre</label>
                            <input type="text" class="form-control" id="name" name="name">
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group">
                            <label for="phone">Telefóno</label>
                            <input type="text" class="form-control" id="phone" name="phone">
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group">
                            <label for="city">Ciudad</label>
                            <input type="text" class="form-control" id="city" name="city">
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email" class="form-control" id="email" name="email">
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group">
                            <label for="address">Dirección</label>
                            <input type="text" class="form-control" id="address" name="address">
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group">
                            <label for="web_site">Sitio Web</label>
                            <input type="text" class="form-control" id="web_site" name="web_site">
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group">
                            <label for="facebook">Facebook</label>
                            <input type="text" class="form-control" id="facebook" name="facebook">
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group">
                            <label for="instagram">Instagram</label>
                            <input type="text" class="form-control" id="instagram" name="instagram">
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group">
                            <label for="contact">Persona Contacto</label>
                            <input type="text" class="form-control" id="contact" name="contact">
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group">
                            <label for="specialties_id">Especialidad</label>
                            <select name="specialties_id" id="specialties_id" class="form-control" enabled>
                                @foreach($specialties as $specialty)
                                    <option value="{{ $specialty->id }}">{{ $specialty->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group">
                            <label for="categories_id">Categoria</label>
                            <select name="categories_id" id="categories_id" class="form-control" enabled>
                                @foreach($categories as $category)
                                    <option value="{{ $category->id }}">{{ $category->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group">
                            <label for="exampleInputFile">Logo</label>
                            <div class="input-group">
                              <div class="custom-file">
                                <input type="file" class="custom-file-input" id="exampleInputFile">
                                <label class="custom-file-label" for="exampleInputFile">Cargar logo</label>
                              </div>
                            </div>
                        </div>
                    </div>
                </div>
              </div>
              <!-- /.card-body -->

              <div class="card-footer">
                  <div class="row">
                    <div class="col-12 text-center">
                        <input type="hidden" class="user_id" id="user_id" name="user_id" value="{{ $user->id }}">
                        <button type="submit" class="btn btn-primary">Guardar</button>
                    </div>
                  </div>
              </div>
            </form>
          </div>
    </div>
@endsection

resources/views/admin/companies/index.blade.php
<?php
?>
@extends('layouts.app')
@section('content')
    <div class="content-wrapper">
        @if($company->count() > 0)
        @else
            <div class="row justify-content-center my-3">
                <a href="{{ url('/admin/companies/create') }}" class="btn btn-primary">Agregar Empresa</a>
            </div>
        @endif
        <table class="table table-hover">
            <thead>
                <tr>
                    <th class="pl-5">Nombre</th>
                    <th>Telefono</th>
                    <th>Especialidad</th>
                    <th class="col-xs-2 text-right pr-5">Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($companies as $c)
                <tr>
                    <td class="pl-5">{{ $c->name }}</td>
                    <td>{{ $c->phone }}</td>
                    <td>
                        @foreach($specialties as $s)
                            @if($c->specialties_id == $s->id)
                                {{ $s->name }}
                            @endif
                        @endforeach
                    </td>
                    <td class="text-right pr-5" >
                        <a href="{{ url('/admin/companies/'.$c->id.'/edit') }}" class="btn_menu">
                            <i class="fa fa-pencil" title="Editar"></i>
                        </a>
                        <a class="btn_menu btn_delete open-modal-del" href="#" data-id="{{ $c->id }}">
                            <i class="fa fa-trash" title="Eliminar"></i>
                        </a>
                    </td>
                </tr>

                @endforeach
            </tbody>
        </table>
        <input type="hidden" name="idselected" id="idselected">
    </div>
@endsection

resources/views/admin/companies/update.blade.php
@extends('layouts.app')
@section('content')
    <div class="content-wrapper">
        <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Editar Empresa</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form  action="{{ route('companies.update',$comp->id) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PATCH')
              <div class="card-body">
                <div class="row">
                    <div class="col-12 col-sm-4">
                        <div class="form-group">
                            <label for="name">Nombre</label>
                            <input type="text" class="form-control" id="name" name="name" value="{{ $comp->name }}">
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group">
                            <label for="phone">Telefóno</label>
                            <input type="text" class="form-control" id="phone" name="phone" value="{{ $comp->phone }}">
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group">
                            <label for="city">Ciudad</label>
                            <input type="text" class="form-control" id="city" name="city" value="{{ $comp->city }}">
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email" class="form-control" id="email" name="email" value="{{ $comp->email }}">
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group">
                            <label for="address">Dirección</label>
                            <input type="text" class="form-control" id="address" name="address" value="{{ $comp->address }}">
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group">
                            <label for="web_site">Sitio Web</label>
                            <input type="text" class="form-control" id="web_site" name="web_site" value="{{ $comp->web_site }}">
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group">
                            <label for="facebook">Facebook</label>
                            <input type="text" class="form-control" id="facebook" name="facebook" value="{{ $comp->facebook }}">
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group">
                            <label for="instagram">Instagram</label>
                            <input type="text" class="form-control" id="instagram" name="instagram" value="{{ $comp->instagram }}">
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group">
                            <label for="contact">Persona Contacto</label>
                            <input type="text" class="form-control" id="contact" name="contact" value="{{ $comp->contact }}">
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group">
                            <label for="specialties_id">Especialidad</label>
                            <select name="specialties_id" id="specialties_id" class="form-control" enabled>
                                @foreach($specialties as $specialty)
                                    <option value="{{ $specialty->id }}" <?php if($specialty->id==$comp->specialties_id){ echo "selected"; } ?>>{{ $specialty->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group">
                            <label for="categories_id">Categoria</label>
                            <select name="categories_id" id="categories_id" class="form-control" enabled>
                                @foreach($categories as $category)
                                    <option value="{{ $category->id }}" <?php if($category->id==$comp->categories_id){ echo "selected"; } ?>>{{ $category->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-12 col-sm-4">
                        <div class="form-group">
                            <label for="exampleInputFile">Logo</label>
                            <div class="input-group">
                                <?php
                                    if($comp->images != 'No Fotos'){
                                ?>
                                        <div class="img-wrap">
                                            <span class="close">&times;</span>
                                            <img src="{{asset('images/logos_companies/'.$comp->images)}}" class="img-fluid">
                                            <input type="hidden" name="url_logo" class="url_logo" value="{{ $comp->images }}">
                                            <input type="hidden" name="id_hotel" class="id_hotel" value="{{ $comp->id }}">
                                        </div>
                                <?php }else{ ?>
                                        <div class="custom-file">
                                            <input id="logo" class="form-control" name="logo" type="file">
                                        </div>
                                <?php } ?>
                            </div>
                        </div>
                    </div>
                </div>
              </div>
              <!-- /.card-body -->

              <div class="card-footer">
                  <div class="row">
                    <div class="col-12 text-center">
                        <button type="submit" class="btn btn-primary">Guardar</button>
                    </div>
                  </div>
              </div>
            </form>
          </div>
    </div>
@endsection